#!/usr/bin/env php
<?php // © 2025 Chitch Contributors, Licensed under the EUPL

require_once 'library/halstead';
require_once 'library/chitch.php';

?>
<?= print_r(
    Halstead\halsteadProject(
        $files = Chitch\getfiles('./', '*.php')
    )
)
?>
